### ISSUE TITLE
Notification Handler Registrations

### ISSUE THREAD

**Issue by cenkjc** [haison8x/MediatR.SimpleInjector#11]
Hi

According to the Mediatr Simple injector examples, notification handlers should be registered as following : 

`container.Collection.Register(typeof(INotificationHandler<>), notificationHandlerTypes);`

instead of : 

`container.Register (typeof (INotificationHandler<>), notificationHandlerTypes);` .

I will create PR regarding to this later.

Reference: 
https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.SimpleInjector/Program.cs

**Comment by haison8x** [comment]
Hi cenkjc

Please help me create PR

Many thanks,
haison8x
