### ISSUE TITLE
MissingFieldException with SimpleInjector V5.x

### ISSUE THREAD

**Issue by knoxi** [haison8x/MediatR.SimpleInjector#14]
Calling 'container.BuildMediator()' throws an exception `Field not found: 'SimpleInjector.Lifestyle.Singleton'` using the latest SimpleInjector V5.0.

Can you check out the latest version of SimpleInjector and migrate your library?

 https://github.com/simpleinjector/SimpleInjector/releases/tag/v5.0.0

**Comment by AdaskoTheBeAsT** [comment]
hi I created more advanced adapter - you can check https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.MediatR.SimpleInjector

**Comment by haison8x** [comment]
https://www.nuget.org/packages/MediatR.SimpleInjector/
