### ISSUE TITLE
RegisterCollection doesn't work with generic types

### ISSUE THREAD

**Issue by LensArt** [haison8x/MediatR.SimpleInjector#6]
Simple injector RegisterCollection doesn't register the generic types from the assemblies. So passing IPipelineBehavior assemblies won't add any registration. Maybe those binding should be removed?

**Comment by haison8x** [comment]
I'm not sure but you may be right

**Comment by LensArt** [comment]
I wanted to register some request pre processors together with the pipeline behaviours needed which made this apparent. There are maybe some options to do this with the assemblies, however I'm not sure if this will be suitable for a generic package: https://simpleinjector.readthedocs.io/en/latest/advanced.html#mixing-collections-of-open-generic-and-non-generic-components

probably the TypesToRegister is the most appropriate but maybe not the nicest :)

**Comment by haison8x** [comment]
@LensArt In my opinion, The pipeline isn't mandatory so that it shouldn't be place in MediatR.SimpleInjector
