### ISSUE TITLE
Lack of license file

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [haison8x/MediatR.SimpleInjector#8]
Hi,

could you please choose license under which you distribute that package?

Thanks

Adam

**Comment by haison8x** [comment]
Dear @AdaskoTheBeAsT 

I have no knowledge about the license so that I don't know how to choose the suitable one. Could you help?

Many thanks,

**Comment by AdaskoTheBeAsT** [comment]
Hi,

I am also not an expert in licensing so I would choose SimpleInjector or Mediatr license type.

SimpleInjector is licensed as MIT  https://github.com/simpleinjector/SimpleInjector/blob/master/licence.txt

Mediatr is licensed as Apache 2.0
https://github.com/jbogard/MediatR/blob/master/LICENSE

Best regards

Adam

**Comment by haison8x** [comment]
Hi @AdaskoTheBeAsT 
I think Apache 2.0 is the most suitable License for this repository

https://github.com/haison8x/MediatR.SimpleInjector/commit/e57a8eabbd95cb5b8e072cb9090e363b311a1b6c
